esphome:
  name: genset
  #friendly_name: blink

rp2040:
  board: rpipicow


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    #key: "8F/nWL+L9T5LSBaBhGkX8xO3T1t9OoZm/Fc/A+4VFs0="
    #key: "C11/kI/6x+g2s0W04604S7N51/Q0rWj7YjYw3Mv52/U="
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "9f6aac9d5e98fb4ba34f158083f13970"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Blink Fallback Hotspot"
    password: "esphomepw"

#-------------------------------------------------------
# Homeassistant I/O code
output: 
  
  # 1. Built-in LED (GPIO 25)
  #- platform: rp2040_pwm # <--- Use PWM output to make 'light: binary' happy
  #  pin: 25
    #id: onboard_led_output
    #frequency: 1000Hz # Required for PWM outputs
  
  # Pi Moroni LED Red (GPIO 6) - MUST BE rp2040_pwm for dimming
  - platform: rp2040_pwm
    pin: GPIO6
    id: led_r
    # Frequency setting is optional, but 1kHz is a good default
    frequency: 1000Hz 
    inverted: true
  
  # Pi Moroni LED Green (GPIO 7) - MUST BE rp2040_pwm
  - platform: rp2040_pwm
    pin: GPIO7
    id: led_g
    frequency: 1000Hz 
    inverted: true
  
  # Pi Moroni LED Blue (GPIO 8) - MUST BE rp2040_pwm
  - platform: rp2040_pwm
    pin: GPIO8
    id: led_b
    frequency: 1000Hz
    inverted: true

#-------------------------------------------------------

# --- LIGHT COMPONENTS (START OF SINGLE LIGHT BLOCK) ---
light: # <--- ONLY ONE 'light:' KEY ALLOWED
  
  # 1. Built-in LED Light
  #- platform: binary 
    #output: onboard_led_output
    #name: "Pico Built-in LED"

  # 3. Pi Moroni Display RGB LED 
  - platform: rgb
    name: "Pico Display RGB LED"
    id: rgb_led_display
    red: led_r
    green: led_g
    blue: led_b
#-------------------------------------------------------



