esphome:
  name: genset
  #friendly_name: blink

rp2040:
  board: rpipicow


# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    #key: "8F/nWL+L9T5LSBaBhGkX8xO3T1t9OoZm/Fc/A+4VFs0="
    #key: "C11/kI/6x+g2s0W04604S7N51/Q0rWj7YjYw3Mv52/U="
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "9f6aac9d5e98fb4ba34f158083f13970"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Blink Fallback Hotspot"
    password: "esphomepw"

#-------------------------------------------------------
# Homeassistant I/O code
output: 
  
  # 1. Built-in LED (GPIO 25)
  #- platform: rp2040_pwm # <--- Use PWM output to make 'light: binary' happy
  #  pin: 25
    #id: onboard_led_output
    #frequency: 1000Hz # Required for PWM outputs
  
  # Pi Moroni LED Red (GPIO 6) - MUST BE rp2040_pwm for dimming
  - platform: rp2040_pwm
    pin: GPIO6
    id: led_r
    # Frequency setting is optional, but 1kHz is a good default
    frequency: 1000Hz 
    inverted: true
  
  # Pi Moroni LED Green (GPIO 7) - MUST BE rp2040_pwm
  - platform: rp2040_pwm
    pin: GPIO7
    id: led_g
    frequency: 1000Hz 
    inverted: true
  
  # Pi Moroni LED Blue (GPIO 8) - MUST BE rp2040_pwm
  - platform: rp2040_pwm
    pin: GPIO8
    id: led_b
    frequency: 1000Hz
    inverted: true

#-------------------------------------------------------

# --- LIGHT COMPONENTS (START OF SINGLE LIGHT BLOCK) ---
light: # <--- ONLY ONE 'light:' KEY ALLOWED
  
  # 1. Built-in LED Light
  #- platform: binary 
    #output: onboard_led_output
    #name: "Pico Built-in LED"

  # 3. Pi Moroni Display RGB LED 
  - platform: rgb
    name: "Pico Display RGB LED"
    id: rgb_led_display
    red: led_r
    green: led_g
    blue: led_b


#-------------------------------------------------------

binary_sensor:

#---------- Pi Moroni buttons ----------------------------------------

  # 2. Display Button A (GPIO 12) - Toggle
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "Display Button A"
    on_press:
      then:
        - light.toggle:
            id: rgb_led_display

  # 3. Display Button B (GPIO 13) - Red
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Display Button B"
    on_press:
      then:
        - light.toggle:
        #- light.turn_on:
            id: rgb_led_display
            #brightness: 75%
            #red: 100%
            #green: 0
            #blue: 0

  # 4. Display Button X (GPIO 14) - Green
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "Display Button X"
    on_press:
      then:
        - light.toggle:
        #- light.turn_on:
            id: rgb_led_display
            #rgb_color: [0, 255, 0] # GREEN
            #brightness: 75%
            #red: 0%
            #green: 100%
            #blue: 0

  # 5. Display Button Y (GPIO 15) - Blue
  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    name: "Display Button Y"
    on_press:
      then:
        - light.toggle:
        #- light.turn_on:
            id: rgb_led_display
            #rgb_color:0 [0, 0, 255] # BLUE
            #brightness: 75%
            #red: 0%
            #green: 0%
            #blue: 100%



#-------------------------------------------------------
# sensor: (This block is fine as it's not duplicated)
sensor:
  - platform: internal_temperature
    name: "Pico Chip Temperature"
    update_interval: 60s
    accuracy_decimals: 1

