#genset.yaml
esphome:
  name: genset
  #friendly_name: genmon2

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "9f6aac9d5e98fb4ba34f158083f13970"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Blink Fallback Hotspot"
    password: "esphomepw"

  # --- On Connect Action for Internal LED ---
  on_connect:
    then:
      - light.turn_on:
          id: onboard_led_light
          brightness: 100% 

#-------------------------------------------------------
# Homeassistant I/O code
output: 
  
  # Output for Built-in LED (GPIO 25)
  - platform: gpio
    pin: GPIO25
    id: onboard_led_output
    
#-------------------------------------------------------

# --- LIGHT COMPONENTS ---
light: 
  
  # Built-in LED Light component
  - platform: binary
    output: onboard_led_output
    id: onboard_led_light
    name: "Pico Built-in LED"


# --- binary_sensor section remains empty ---

#------------------------------------------------------
# Sensors & Text Sensors
sensor:
  - platform: internal_temperature
    id: pico_chip_temperature
    name: "Pico Chip Temperature"
    update_interval: 60s
    accuracy_decimals: 1

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Current IP Address"
      id: ip_address_sensor
      update_interval: 10s

#------------------------------------------------------
# Display Configuration: Pulled in from external file
<<: !include functions.yaml
