#genset.yaml
esphome:
  name: genset
  #friendly_name: genmon2

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "9f6aac9d5e98fb4ba34f158083f13970"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Blink Fallback Hotspot"
    password: "esphomepw"

  # --- On Connect Action for Internal LED ---
  on_connect:
    then:
      - light.turn_on:
          id: onboard_led_light
          brightness: 100% 

#-------------------------------------------------------
# Homeassistant I/O code
output: 
  
  # Output for Built-in LED (GPIO 25)
  - platform: gpio
    pin: GPIO25
    id: onboard_led_output
    
#-------------------------------------------------------

# --- LIGHT COMPONENTS ---
light: 
  
  # Built-in LED Light component
  - platform: binary
    output: onboard_led_output
    id: onboard_led_light
    name: "Pico Built-in LED"

#------------------------------------------------------
# MQTT Integration
mqtt:
  broker: 192.168.1.5 # <-- REPLACE with your MQTT Broker IP Address
  port: 1883
  username: esphome
  password: !secret mqtt_password
  
  # Publish a heartbeat to the homeassistant status topic every 60 seconds
  # The status topic name will be 'homeassistant/status' by default.
  status_topic: homeassistant/status
  
  # Enable text sensor to monitor MQTT connection status for the display
  on_status_change:
    - then:
        - text_sensor.template.publish:
            id: mqtt_status_sensor
            state: ${is_connected} ? "Connected" : "Disconnected"

#------------------------------------------------------
# ADC Input Setup 
adc:
  # This section enables the ADC component

#------------------------------------------------------
# Sensors & Text Sensors
sensor:
  - platform: internal_temperature
    id: pico_chip_temperature
    name: "Pico Chip Temperature"
    update_interval: 60s
    accuracy_decimals: 1

  # --- ADC INPUTS: ADC1 (GPIO27) and ADC2 (GPIO28) adjacent to AGND ---
  - platform: adc
    pin: GPIO27 # Pin 32 (ADC1) - Battery Voltage
    name: "Battery Voltage"
    id: battery_voltage
    update_interval: 5s
    # unit_of_measurement: V
    # accuracy_decimals: 2
    # lambda: return x * 5.0 / 4095.0 * 10.0; # Example scaling

  - platform: adc
    pin: GPIO28 # Pin 34 (ADC2) - Armed Status
    name: "Armed"
    id: armed 
    update_interval: 5s
    # unit_of_measurement: V
    # accuracy_decimals: 2

# --- Text Sensor to capture IP Address ---
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Current IP Address"
      id: ip_address_sensor
      update_interval: 10s
      
  # Text sensor to show MQTT status (Updated by 'on_status_change' above)
  - platform: template
    name: "MQTT Status"
    id: mqtt_status_sensor
    # This sensor will be populated via the lambda in the MQTT section

#-------------------------------------------------------
# --- BINARY SENSORS ---
# (Binary sensors remain unchanged)
binary_sensor:
# ... (omitted for brevity, content is unchanged) ...

  # 1. Mains/Generator Status Sensors (GPIO 18-21)
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Mains"
    id: mains

  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Gen Phase 1"
    id: gen_phase_1

  - platform: gpio
    pin:
      number: GPIO20
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Gen Phase 2"
    id: gen_phase_2

  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Alarm"
    id: alarm

  # 2. Control Logic Inputs (GPIO 10-13)
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Transfer Switch"
    id: xfer_sw

  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Starting"
    id: starting

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Run Enabled"
    id: run_enabled

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Spare 1"
    id: spare_1

  # 3. Engine Status/Alarm LEDs (GPIO 6-9)
  - platform: gpio
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Low Oil"
    id: low_oil

  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Over Temp"
    id: over_temp

  - platform: gpio
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Over Crank"
    id: over_crank

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Over Speed"
    id: over_speed


#------------------------------------------------------
# Display Configuration: Pulled in from external file
<<: !include functions.yaml
