#genset.yaml
esphome:
  name: genset
  #friendly_name: genmon2

rp2040:
  board: rpipicow

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: "9f6aac9d5e98fb4ba34f158083f13970"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Blink Fallback Hotspot"
    password: "esphomepw"

  # --- On Connect Action for Internal LED ---
  on_connect:
    then:
      - light.turn_on:
          id: onboard_led_light
          brightness: 100% 

#-------------------------------------------------------
# Homeassistant I/O code
output: 
  
  # Output for Built-in LED (GPIO 25)
  - platform: gpio
    pin: GPIO25
    id: onboard_led_output
    
#-------------------------------------------------------

# --- LIGHT COMPONENTS ---
light: 
  
  # Built-in LED Light component
  - platform: binary
    output: onboard_led_output
    id: onboard_led_light
    name: "Pico Built-in LED"

#------------------------------------------------------
# MQTT Integration
#mqtt:
  #id: mqtt_client
  #broker: 172.16.30.41
  #port: 1883
  #username: esphome
  #password: !secret mqtt_password

  # additional params
  #topic_prefix: esphome

# Status configuration (using the documented structure)
  #status:
    #topic: homeassistant/status
    #update_interval: 60s # Publish status every 60 seconds (optional, but good practice)

# Birth message (Sends "online" when connected)
  #birth_message:
    #topic: homeassistant/genset/status
    #payload: "online"
    #qos: 1
    #retain: true
    
  # Will message (Broker sends "offline" if connection is lost)
  #will_message:
    #topic: homeassistant/genset/status
    #payload: "offline"
    #qos: 1
    #retain: true

#------------------------------------------------------
# Sensors & Text Sensors
sensor:
  - platform: internal_temperature
    id: pico_chip_temperature
    name: "Pico Chip Temperature"
    update_interval: 60s
    accuracy_decimals: 1

  # --- ADC INPUTS: ADC1 (GPIO27) and ADC2 (GPIO28) adjacent to AGND ---
  - platform: adc
    pin: GPIO27 # Pin 32 (ADC1) - Battery Voltage
    name: "Battery Voltage"
    id: battery_voltage
    update_interval: 5s
    unit_of_measurement: V
    accuracy_decimals: 1
    # lambda: return x * 5.0 / 4095.0 * 10.0; # Example scaling

  - platform: adc
    pin: GPIO28 # Pin 34 (ADC2) - Armed Status
    name: "Armed ADC"
    id: armed_adc 
    update_interval: 5s
    unit_of_measurement: V
    accuracy_decimals: 1

# --- Text Sensor to capture IP Address ---
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "Current IP Address"
      id: ip_address_sensor
      update_interval: 10s
      
# Text sensor to show MQTT status
  #- platform: template
    #name: "MQTT Status"
    #id: mqtt_status_sensor
    # Using the YAML Flow Block Scalar (|-): This guarantees the C++ is treated as raw text.
    #lambda: |- 
      #if (id(mqtt_client).connected) {
        #return "Connected";
      #} else {
        #return "Disconnected";
      #}
    #update_interval: 15s

#-------------------------------------------------------
# --- BINARY SENSORS ---
binary_sensor:

  # 1. Mains/Generator Status Sensors (GPIO 18-21)
  - platform: gpio
    pin:
      number: GPIO18
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Mains"
    id: mains

  - platform: gpio
    pin:
      number: GPIO19
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Gen Phase 1"
    id: gen_phase_1

  - platform: gpio
    pin:
      number: GPIO20
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Gen Phase 2"
    id: gen_phase_2

  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Alarm"
    id: alarm_status

  # 2. Control Logic Inputs (GPIO 10-13)
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Transfer Switch"
    id: xfer_sw

  - platform: gpio
    pin:
      number: GPIO11
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Starting"
    id: starting

  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Run Enabled"
    id: run_enabled

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Spare 1"
    id: spare_1

  # 3. Engine Status/Alarm LEDs (GPIO 6-9)
  - platform: gpio
    pin:
      number: GPIO6
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Low Oil"
    id: low_oil

  - platform: gpio
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Over Temp"
    id: over_temp

  - platform: gpio
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Over Crank"
    id: over_crank

  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true # Active Low
    name: "Over Speed"
    id: over_speed

  # New Binary Sensor: ON when voltage is high (Armed)
  - platform: template
    name: "Armed"
    id: armed 
    # Use the new armed_adc ID
    # assumes cathode of led pulled to ground to illuminate
    lambda: return id(armed_adc).state < 1.0; 
    device_class: safety

#------------------------------------------------------
# Display Configuration: Pulled in from external file
<<: !include functions.yaml
